env:
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
overrides: 
  - files: ["*.graphql"]
    parser: "@graphql-eslint/eslint-plugin"
    plugins: ["@graphql-eslint"]
    # parserOptions:
    #   schema: "./src/schema.graphql"

